# Generated by Django 4.0.5 on 2022-06-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrw_id', models.PositiveIntegerField()),
                ('fallback_name', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=16)),
                ('media_id_ref', models.CharField(max_length=64)),
                ('geo_coordinate_type', models.CharField(max_length=16)),
                ('geo_coordinate_x', models.FloatField()),
                ('geo_coordinate_y', models.FloatField()),
                ('stars', models.PositiveSmallIntegerField()),
                ('address_street', models.CharField(max_length=32)),
                ('address_zipcode', models.CharField(max_length=16)),
                ('contact_phone', models.CharField(max_length=16)),
                ('contact_email', models.CharField(max_length=32)),
                ('contact_url', models.CharField(max_length=32)),
                ('heliosUrl', models.CharField(max_length=64)),
                ('is_booking_com_block_enabled', models.BooleanField(default=False)),
                ('is_premium_ad_link_enabled', models.BooleanField(default=False)),
                ('owner_id', models.CharField(max_length=64)),
                ('status_published', models.BooleanField(default=False)),
                ('status_checked', models.BooleanField(default=False)),
                ('status_reason', models.CharField(max_length=32)),
                ('id_ref', models.CharField(max_length=32)),
                ('helios_id', models.PositiveBigIntegerField()),
                ('updated_date', models.DateTimeField()),
                ('popularity_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HeliosHistoricalUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_url', models.CharField(max_length=64)),
                ('new_url', models.CharField(max_length=64)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ref', models.CharField(max_length=32)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ref', models.CharField(max_length=32)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('w', 'winner'), ('r', 'recommended')], max_length=32)),
                ('date', models.DateTimeField()),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodations.accommodation')),
            ],
        ),
    ]
