# Generated by Django 4.0.5 on 2022-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='heliosUrl',
            new_name='helio_url',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='id_ref',
            field=models.CharField(max_length=60),
        ),
    ]
