# Generated by Django 4.0.5 on 2022-06-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_rename_heliosurl_accommodation_helio_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='helio_url',
            new_name='helios_url',
        ),
    ]
