# Generated by Django 4.0.5 on 2022-06-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_rename_helio_url_accommodation_helios_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationaward',
            name='date',
        ),
        migrations.AddField(
            model_name='accommodationaward',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
