# Generated by Django 4.0.5 on 2022-06-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0004_remove_accommodationaward_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationfacility',
            name='id_ref',
            field=models.CharField(max_length=64),
        ),
    ]
