# Generated by Django 4.0.5 on 2022-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_alter_accommodationfacility_id_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationparents',
            name='id_ref',
            field=models.CharField(max_length=63),
        ),
    ]
