# Generated by Django 4.0.5 on 2022-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_alter_accommodationparents_id_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='address_street',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='contact_email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='contact_phone',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='contact_url',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='helios_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='media_id_ref',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='owner_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='status_reason',
            field=models.CharField(max_length=128),
        ),
    ]
