# Generated by Django 4.0.5 on 2022-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0008_alter_accommodation_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helioshistoricalurl',
            name='new_url',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='helioshistoricalurl',
            name='old_url',
            field=models.CharField(max_length=128),
        ),
    ]
