# Generated by Django 4.0.5 on 2022-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0010_alter_accommodationaward_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='id_ref',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
