# Generated by Django 4.0.5 on 2022-06-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0011_alter_accommodation_id_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='id_ref',
            field=models.CharField(max_length=60),
        ),
    ]
