# Generated by Django 4.0.5 on 2022-06-25 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_review_advancedskiarea_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ref', models.CharField(max_length=32)),
                ('original_name', models.CharField(max_length=256)),
                ('original_email', models.EmailField(max_length=256)),
                ('original_ip', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.customuser'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
