# Generated by Django 4.0.5 on 2022-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_customuser_alter_review_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_ref',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='original_name',
            field=models.CharField(max_length=64),
        ),
    ]
