# Generated by Django 4.0.5 on 2022-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_customuser_original_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='general_review',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='status_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='status_reason',
            field=models.TextField(null=True),
        ),
    ]
