# Generated by Django 4.0.5 on 2022-06-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_review_general_review_review_status_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cooperation_syndication_partner_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_review',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='traveled_with',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
