# Generated by Django 4.0.5 on 2022-06-28 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0012_alter_accommodation_id_ref'),
        ('review', '0010_review_accommodation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='id_ref',
            field=models.CharField(default=0, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_ref',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_user', to='accommodations.accommodation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='review.customuser'),
        ),
        migrations.AlterField(
            model_name='reviewparent',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_parent', to='review.review'),
        ),
        migrations.AlterField(
            model_name='reviewtext',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_text', to='review.review'),
        ),
        migrations.AlterField(
            model_name='reviewtitle',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_title', to='review.review'),
        ),
    ]
