# Generated by Django 4.0.5 on 2022-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_review_id_ref_alter_customuser_id_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id_ref',
            field=models.CharField(max_length=64),
        ),
    ]
